version: "3.8"

services:
  db:
    image: postgis/postgis:13-3.1
    container_name: openmaint-db
    environment:
      POSTGRES_USER: openmaint
      POSTGRES_PASSWORD: openmaint
      POSTGRES_DB: openmaint
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  openmaint:
    build: ./openmaint
    container_name: openmaint-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: openmaint
      DB_USER: openmaint
      DB_PASS: openmaint

volumes:
  db_data:
